# General
author: Jason Ho
author-about:
  en: Statisticsian
  cn: 统计师
title: Have you tried turning it off and on again?
description: >- # this means to ignore newlines until "baseurl:"
  This site consists my recent works/projects and study notes.
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com

# Page settings
highlight-post-max: 4
homepage-post-max:  30
split-txt:          "%#%"
weighted-txt:       "zzz$"

# Social settings
social-github: sleepyjason
social-twitter:
social-facebook:
social-linkedin:
social-email: mail2jasonho@foxmail.com

# Image settings
image-url: "/assets/img/"
sample-image-url: "/assets/img/samples/"
post-image-url: "assets/img/post/"
sample-image-max: 6
home-banner-image: "home-banner.png"
home-author-image: "jasonho.jpg"



# Build settings
markdown: kramdown
theme: minima
plugins:
  - jekyll-feed

# Language setting
# lang_select: true
# default_lang: en

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
